### lab9 image has our dependencies
image: registry.seng4110.tru.ca/trevordrayton/docker/seng4110:lab9

stages:
  - build
  - test
  - docs

build-job:
  stage: build
  script:
    - echo " Compiling the code ..."
    - mkdir build
    - cd build
    - cmake ..
    - make
    - ./project 9.8 iron 30.0 0.0

unit-test-job:
  stage: test
  rules:
    - if: '$CI_COMMIT_BRANCH == "test"'
      when: always
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: always
    - when: never
  script:
    - echo " Running unit tests ..."
    - mkdir build
    - cd build
    - cmake ..
    - make
    - ./runtest

docs-job:
  stage: docs
  rules:
    - if: '$CI_COMMIT_BRANCH == "doc"'
      when: always
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: always
  script: 
    - cd docs
    - doxygen /builds/trevordrayton/Project/docs/Doxyfile
    - doxygen
    - source /usr/bin/make-json.bash token=$API_TOKEN project=$CI_PROJECT_ID job=$CI_JOB_ID name=$CI_PROJECT_NAME secret=$WEBHOOK_SECRET slug=$CI_PROJECT_PATH_SLUG > out.json
  artifacts:
    paths:
      - docs/
    expire_in: 30min
    