### lab7 image has our dependencies
image: registry.seng4110.tru.ca/trevordrayton/docker/seng4110:lab7

stages:
  - build
  - test
  - docs
  - dependency
  - coverage

build-job:
  stage: build
  script:
    - echo " Compiling the code ..."
    - mkdir build
    - cd build
    - cmake ..
    - make
    - ./lab7

unit-test-job:
  stage: test
  rules:
    - if: '$CI_COMMIT_BRANCH == "test"'
      when: always
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: always
    - when: never
  script:
    - echo " Running unit tests ..."
    - mkdir build
    - cd build
    - cmake ..
    - make
    - ./runtest

docs-job:
  stage: docs
  rules:
    - if: '$CI_COMMIT_BRANCH == "doc"'
      when: always
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: always
  script: 
    - cd docs
    - doxygen /builds/trevordrayton/lab7/docs/Doxyfile
    - doxygen
    - source /usr/bin/make-json.bash token=$API_TOKEN project=$CI_PROJECT_ID job=$CI_JOB_ID name=$CI_PROJECT_NAME secret=$WEBHOOK_SECRET slug=$CI_PROJECT_PATH_SLUG > out.json
  artifacts:
    paths:
      - docs/
    expire_in: 30min
    
dependency-job:
  stage: dependency
  rules:
    - if: '$CI_COMMIT_BRANCH == "dependency"'
      when: always
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: always
  script: 
    - mkdir build
    - cd build
    - cmake ..
    - make graph
  artifacts:
    paths:
      - build/dependency_graph.png
    expire_in: 30min
coverage-job:
  stage: coverage
  rules:
    - if: '$CI_COMMIT_BRANCH == "coverage"'
      when: always
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: always
  script: 
    - mkdir coverage
    - cd coverage
    - cmake ..
    - make IntegrationNextDate_coverage
  artifacts:
    paths:
      - coverage/IntegrationNextDate_coverage
    expire_in: 30min